export default {
  //connect
  CONNECT_START: "CONNECT_START",
  CONNECT_END: "CONNECT_END",
  CONNECT_ERROR: "CONNECT_ERROR",
  // movie
  GET_MOVIES: "GET_MOVIES",
  // error
  ERROR_HAPPEN: "ERROR_HAPPEN",
  ERROR_CONFIRM: "ERROR_CONFIRM",
  // user
  USER_LOGIN: "USER_LOGIN",
  USER_REGISTER: "USER_REGISTER"
};
